-- Create Database
CREATE DATABASE OnlineBookStore;
USE OnlineBookstore;

-- Create Tables
Drop TABLE IF EXISTS Books;
CREATE TABLE Books (
Book_ID SERIAL PRIMARY KEY, 
Title VARCHAR(100),
Author VARCHAR(100),
Genre VARCHAR(50),
Published_Yeat INT,
Price NUMERIC(10, 2),
Stock INT 
);

DROP TABLES IF EXISTS Customers;
CREATE TABLE Customers (
Customer_ID SERIAL PRIMARY KEY,
Name VARCHAR(100),
Email VARCHAR(100),
Phone VARCHAR(15),
City VARCHAR(50),
Country VARCHAR(150)
);

DROP TABLES IF EXISTS Orders;
CREATE TABLE Orders (
Order_ID SERIAL PRIMARY KEY,
Customer_ID INT REFERENCES Customers(Customer_ID),
Book_ID INT REFERENCES Books(Book_ID),
Order_date DATE,
Quantity INT,
Total_amount NUMERIC (10, 2)
);

-- Now Data Import 

-- Sales Analysis 
-- Show All Tables
SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

-- 1. Find the total revenue generated from all orders.
SELECT SUM(total_amount) AS total_revenue
FROM orders;

-- 2. Calculate the total revenue generated by each book.
SELECT book_id, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY book_id;

-- 3. Find the top 5 books generating the highest revenue.
SELECT book_id, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY book_id
ORDER BY total_revenue DESC
LIMIT 5;

-- 4. Calculate total revenue generated by each genre.
SELECT b.genre, SUM(o.total_amount) AS total_revenue
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.genre;

-- 5. Find the monthly revenue trend based on order date.
SELECT MONTH(total_amount) AS months, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY months;

-- 6. Find the average order value across all orders.
SELECT order_id, AVG(total_amount) AS avg_order
FROM orders
GROUP BY order_id;

-- 7. Identify the highest single order amount.
SELECT MAX(total_amount) AS Max_order
FROM orders;

-- 8. Find total quantity of books sold for each book.
SELECT b.title, SUM(o.quantity) AS total_qty
FROM orders o
JOIN books b
ON b.book_id = o.book_id
GROUP BY title
ORDER BY title;

-- 9. Calculate revenue generated by each author.
SELECT b.author, SUM(o.total_amount) AS total_revenue
FROM orders o
JOIN books b
ON b.book_id = o.book_id
GROUP BY author
ORDER BY author;

-- 10. Identify the day with the highest sales amount.
SELECT DAY(order_date) AS Days, SUM(total_amount) AS total_sales
FROM orders
GROUP BY days
ORDER By total_sales DESC
LIMIT 1;

-- Customer Analysis
-- 11. Find the top 5 customers who spent the most money.
SELECT c.name, SUM(o.total_amount) AS total_spent 
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY total_spent DESC
LIMIT 5;

-- 12. Calculate the total number of orders placed by each customer.
SELECT c.name, SUM(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY total_orders;

-- 13. Find customers whose total spending is above the average spending.
SELECT c.name, SUM(o.total_amount) AS total_spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING total_spending > (SELECT AVG(total_amount) FROM orders);

-- 14. Identify customers who never placed an order.
SELECT c.name, order_id
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE order_id IS NULL;

-- 15. Find repeat customers who placed more than one order.
SELECT c.name, COUNT(o.order_id) AS count_order
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING count_order > 1;

-- 16. Calculate the average order value for each customer.
SELECT c.name, AVG(o.total_amount) AS avg_order
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY c.name;

-- 17. Find the customer who made the highest single purchase.
SELECT c.name, o.total_amount
FROM orders o
JOIN customers c 
ON o.customer_id = c.customer_id
ORDER BY o.total_amount DESC
LIMIT 1;

-- 18. Calculate the number of customers in each country.
SELECT country, COUNT(customer_id) AS count_customer
FROM customers
GROUP BY country;

-- 19. Find customers who purchased more than 5 books in total.
SELECT o.customer_id,  COUNT(b.book_id) AS count_books 
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY o.customer_id
HAVING count_books > 5;

-- 20. Rank customers based on total spending.
SELECT customer_id, SUM(total_amount) AS total_spending, 
RANK() OVER (ORDER BY SUM(total_amount) DESC) AS rnk
FROM orders
GROUP BY customer_id; 

-- Book Performance Analysis
-- 21. Find the most sold book based on quantity.
SELECT b.title, SUM(o.quantity) AS total_sold
FROM orders o
JOIN books b ON o.book_id = b.book_id
GROUP BY b.title
ORDER BY total_sold DESC
LIMIT 1;

-- 22. Identify the top 10 best-selling books.
SELECT b.title, SUM(o.quantity) AS total_sold
FROM orders o
JOIN books b ON o.book_id = b.book_id
GROUP BY b.title
ORDER BY total_sold DESC
LIMIT 10;

-- 23. Find books that have never been ordered.
SELECT book_id
FROM books 
WHERE book_id NOT IN( SELECT book_id FROM orders);

-- 24. Calculate the average price of books in each genre.
SELECT genre, AVG(price) AS avg_price
FROM books
GROUP BY genre;

-- 25. Identify the most expensive book in the catalog.
SELECT title, price 
FROM books
ORDER BY price DESC
LIMIT 1;

-- 26. Find the cheapest book.
SELECT title, price 
FROM books
ORDER BY price ASC
LIMIT 1;

-- 27. Calculate the total inventory value (price × stock).
SELECT SUM(price * stock) AS inventory_value
FROM books;

-- 28. Find total books sold by each author.
SELECT b.author, SUM(o.quantity) AS total_book_sold
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.author
ORDER BY total_book_sold DESC;

-- 29. Rank genres based on total stock available.
SELECT genre, SUM(stock) AS total_stock, RANK() OVER (ORDER BY SUM(stock) DESC) AS rnk
FROM books 
GROUP BY genre;

-- 30. Find books priced above the average book price.
SELECT title, price 
FROM books
WHERE price > (SELECT AVG(price) FROM books);

-- Order Analysis
-- 31. Rank all orders based on total amount.
SELECT order_id, total_amount AS total_orders, 
RANK() OVER (ORDER BY total_amount DESC) rnk
FROM orders;

-- 32. Calculate the running total of revenue by order date.
SELECT order_date, SUM(total_amount) OVER (ORDER BY order_date) AS running_revenue
FROM orders;

-- 33. Find the percentage contribution of each order to total revenue.
SELECT order_id, total_amount, (total_amount *100.0 / SUM(total_amount) OVER() ) AS percentage_revenue 
FROM orders;

-- 34. Compare the current order amount with the previous order amount.
SELECT order_id, total_amount, LAG(total_amount) OVER (ORDER BY order_date) AS previous_order_amount
FROM orders;

-- 35. Find the next order amount using LEAD function.
SELECT order_date, total_amount, LEAD(total_amount) OVER (order BY order_date) AS next_oder_amount
FROM orders;

-- 36. Rank customers based on total revenue generated.
SELECT customer_id, SUM(total_amount) AS total_revenue,
RANK() OVER (ORDER BY SUM(total_amount) DESC) AS rnk
FROM orders
GROUP BY customer_id;

-- 37. Assign a row number to each order for every customer based on order date.
SELECT order_id, customer_id, order_date, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC) AS rnk
FROM orders;

-- 38. Identify the first order placed by each customer.
SELECT *
FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date ) AS rnk FROM orders)t
WHERE rnk = 1;

-- 39. Find the highest value order for each customer.
SELECT * 
FROM (SELECT *, RANK() OVER (PARTITION BY customer_id ORDER BY total_amount DESC) AS rnk
FROM orders) t
WHERE rnk = 1;
 
-- 40. Calculate revenue percentage contributed by each customer.
SELECT customer_id, SUM(total_amount) AS customer_revenue, 
(SUM(total_amount)*100 / SUM(SUM(total_amount)) OVER ()) AS revenue_percentage
FROM orders
GROUP BY customer_id;

-- CASE Statement Analysis
-- 41. Categorize orders into High, Medium, and Low value orders based on total amount.
SELECT order_id, total_amount,
	CASE 
		WHEN total_amount > 180 THEN 'High value'
		WHEN total_amount BETWEEN 180 AND 100 THEN 'Mediumvalue'
        ELSE 'Low value'
	END AS order_category
FROM orders;

-- 42. Categorize books as Expensive or Affordable based on price.
SELECT book_id, price,
	CASE
		WHEN price > 40 THEN 'Expensive'
        ELSE 'Affordable'
	END AS price_category
FROM books;

-- 43. Classify customers as VIP or Regular based on their total spending. 
SELECT c.name, SUM(o.total_amount) AS total_spending,
	CASE
		WHEN SUM(o.total_amount) > 180 THEN 'VIP customer'
        ELSE 'Regular customer'
    END AS classify_customer    
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.name;
	
-- 44. Categorize genres as Top Performing or Normal based on total revenue.
SELECT b.genre, SUM(o.total_amount) AS total_revenue,
	CASE
		WHEN SUM(o.total_amount) > 10000 THEN 'Top genres'
        ELSE 'Normal genres'
	END AS categorize_genres
FROM orders o
JOIN books b
ON b.book_id = o.book_id
GROUP BY genre;

-- 45. Create a stock status column (Out of Stock, Low Stock, Available).
SELECT stock,
	CASE
		WHEN stock = 0 THEN 'Out of stock'
        WHEN stock < 10 THEN 'Low stock'
        ELSE 'Available'
	END AS stock_status
FROM books;

-- 46. Categorize books into Old vs New books based on published year.
SELECT published_year,
	CASE
		WHEN published_year > 1998 THEN 'New Books'
        ELSE 'Old Books'
	END AS categorize_books
FROM books;
    
-- 47. Identify high-demand books based on quantity sold.
SELECT b.title, o.quantity,
	CASE
		WHEN o.quantity > 5 THEN 'High-demand Book'
        ELSE 'Low-demand Book'
	END AS book_status
FROM books b
JOIN orders o
ON b.book_id = o.book_id;

-- 48. Categorize customers based on number of orders placed.
SELECT c.name, COUNT(o.order_id) AS total_orders,
	CASE
		WHEN COUNT(o.order_id) >= 3 THEN 'Frequent Customer'
        ELSE 'Ocassional Customer'
	END AS customer_category
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name;

-- 49. Create order size categories based on quantity purchased.
SELECT order_id, quantity,
	CASE
		WHEN quantity >= 10 THEN 'Bulk order'
        WHEN quantity BETWEEN 5 AND 9 THEN 'Medium order'
		ELSE 'Small order'
	END AS order_size
    FROM orders;
    
-- 50. Classify authors based on total sales generated.
SELECT b.author, SUM(o.total_amount) AS total_sales,
	CASE
		WHEN SUM(o.total_amount) > 145 THEN 'Top Author'
        ELSE 'Average Author'
	END AS Author_Category
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.author;

-- Advanced Level
-- 51. Find customers whose spending is above the overall average order value.
SELECT c.name, SUM(o.total_amount) AS total_spending
FROM orders o
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING total_spending > (SELECT AVG(total_amount) FROM orders);

-- 52. Identify the top performing genre using a CTE.
WITH genre_sales AS (
SELECT b.genre, SUM(o.total_amount) AS revenue 
FROM orders o
JOIN books b
ON b.book_id = o.book_id 
GROUP BY b.genre)
SELECT * FROM genre_sales 
ORDER BY revenue DESC;

-- 53. Find customers who ordered books from multiple genres. 
SELECT c.name, COUNT(DISTINCT b.genre) AS count_genre
FROM orders o
JOIN books b ON o.book_id = b.book_id
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.name
HAVING count_genre > 1;

-- 54. Identify books that appear in both the books table and orders table using INTERSECT.
SELECT book_id FROM books
INTERSECT
SELECT book_id FROM orders;

-- 55. Find customers present in customers table but not in orders using EXCEPT.
SELECT customer_id FROM customers
EXCEPT
SELECT customer_id FROM orders;

-- 56. Combine customer IDs from orders and customers using UNION.
SELECT customer_id FROM customers
UNION 
SELECT customer_id FROM orders;

-- 57. Find authors who sold more books than the average author sales.
SELECT b.author, SUM(o.quantity) AS book_sold
FROM orders o
JOIN books b
ON o.book_id = b.book_id
GROUP BY b.author
HAVING book_sold > (SELECT AVG(total_books) FROM 
							(SELECT SUM(quantity) AS total_books FROM orders GROUP BY book_id)t
);

-- 58. Identify books whose total sales exceed the average book sales.
SELECT b.title, SUM(o.total_amount) AS total_sales
FROM orders o
JOIN books b
ON o.book_id = b.book_id
GROUP BY b.title
HAVING total_sales > (SELECT AVG(book_sales) FROM(SELECT SUM(total_amount) AS book_sales FROM books GROUP BY book_id)t
);

-- 59. Find the top 3 revenue-generating authors using a CTE.
WITH author_sales AS (SELECT b.author, SUM(o.total_amount) AS revenue
						FROM books b
                        JOIN orders o
                        ON b.book_id = o.book_id
                        GROUP BY b.author)
SELECT * FROM author_sales 
ORDER BY revenue
LIMIT 3;

-- 60. Identify customers whose total spending ranks in the top 10%.
SELECT * 
FROM ( SELECT c.name, SUM(o.total_amount) AS total_spending, 
NTILE(10) OVER (ORDER BY SUM(o.total_amount) DESC) AS spending_rnk
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name) t
WHERE spending_rnk = 1;
