USE prodcat;
-- using joins
-- 1. Show all transactions with their product category name
SELECT t.transaction_id, t.total_amt, p.prod_cat
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t. prod_cat_code = p.prod_cat_code;

-- 2. List each transaction with customer gender and total amount.
SELECT t.transaction_id, c.Gender, t.total_amt
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_id;

-- 3. Show product category and subcategory for each transaction.
SELECT t.transaction_id, p.prod_cat, p.prod_subcat
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code;

-- 4. Get the total quantity purchased by each customer city.
SELECT c.city_code, SUM(t.Qty) As Total_Qty
FROM customer.custdata c
JOIN transactions.transdata t
ON c.customer_Id = t.cust_id
GROUP BY c.city_code;

-- 5. Retrive the total revenue generated per product category.
SELECT p.prod_cat, SUM(t.total_amt) as Total_Revenue
FROM prodcat.prodata p
JOIN transactions.transdata t
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 6. Show each transaction with customer city and product subcategory name.
SELECT t.transaction_id, c.city_code, p.prod_subcat 
FROM transactions.transdata t
JOIN customer.custdata c
ON c.customer_Id = t.cust_id 
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code;

-- 7. Find the number of transactions done by each gender.
SELECT c.gender, COUNT(transaction_id) As Total
FROM transactions.transdata t
JOIN customer.custdata c
ON c.customer_Id = t.cust_id
GROUP BY c.gender;

-- 8. List all customers who purchased from more than one store type.
SELECT c.customer_id, COUNT(DISTINCT t.store_type) As Storetype
FROM transactions.transdata t
JOIN customer.custdata c
ON c.customer_Id = t.cust_id
GROUP BY c. customer_Id
HAVING COUNT(DISTINCT t.store_type) > 1;

-- 9.show the avg tax paid per product category.
SELECT p.prod_cat, AVG(t.tax) As AVG_tax
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 10. Retrive transactions along with customer date of bith and product category. 
SELECT t.transaction_id, c.DOB, p.prod_cat, t.total_amt
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code;

-- 11. Find total revenue per store type and product category combination.
SELECT t.store_type, p.prod_cat, SUM(t.total_amt) AS Total_revenue
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY t.store_type, p.prod_cat;

-- 12. Show all transactions where the customer's city is the same as city_code='10'
SELECT t.transaction_id, t.total_amt, c.city_code
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
WHERE c.city_code = 10;


-- 13. Find the total quantity sold per product subcategory.
SELECT p.prod_subcat, SUM(t.Qty) As Total_Qty
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code AND t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_subcat;

-- 14. Show the most expensive transaction(highest total amount) with product category name.
SELECT t.transaction_id, p.prod_cat, t.total_amt
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
ORDER BY t.total_amt DESC
LIMIT 1;

-- 15. Show the oldest customer transaction details.
SELECT t.transaction_id, c.DOB, t.total_amt
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
ORDER BY c.DOB DESC
LIMIT 1;

-- 16. Find the total revenue generated by customers of each geneder.
SELECT c.gender, SUM(t.total_amt) AS Total_revenue
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.gender;

-- 17. Show all trasactions along with product subcategory where Qty > 3.
SELECT t.transaction_id, t.Qty, p.prod_subcat
FROM transactions.transdata t 
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE t.Qty > 3;

-- 18. Retrive the total tax collected from each store type.
SELECT store_type, SUM(tax) AS Total_tax
FROM transactions.transdata
GROUP BY store_type;

-- 19. Find customer who never purchased from "Online store type".
SELECT c.customer_Id, t.transaction_id
FROM customer.custdata c
LEFT JOIN transactions.transdata t
ON t.cust_id = c.customer_Id AND t.store_type = "e-shop" 
WHERE t.transaction_id IS NULL;

-- 20. Show top 5 product categories based on total revenue.
SELECT p.prod_cat, SUM(t.total_amt) As Total_revenue
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat
ORDER BY Total_revenue DESC
LIMIT 5;

-- 21. Find the average total amount spent per product subcategory in each city.
SELECT p.prod_subcat, c.city_code, AVG(t.total_amt) AS Total_Avg
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat, c.city_code;

-- 22. Identify the top 3 product subcategories for each store type based on revenue
SELECT p.prod_subcat, t.store_type, SUM(t.total_amt) As Total_revenue
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat, t.Store_type
ORDER BY t.Store_type, Total_revenue DESC
LIMIT 3;

-- 23. Find the number of unique customers per store type.
SELECT store_type, COUNT(DISTINCT total_amt) As Unique_cust
FROM transactions.transdata
GROUP BY store_type;

-- 24. Find the product category with the highest number of unique customers.
SELECT p.prod_cat, COUNT(DISTINCT t.cust_id) AS Unique_cust
FROM prodcat.prodata p
JOIN transactions.transdata t
ON p.prod_cat_code = t.prod_cat_code
GROUP BY p.prod_cat
ORDER BY Unique_cust DESC
LIMIT 1;

-- 25. Find the total tax and avg tax for each product category.
SELECT p.prod_cat, SUM(t.tax) AS Total_tax, AVG(t.tax) As Avg_tax
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- using subquery

-- 26. Find all customers who made at least one purchase.
SELECT customer_id, city_code, gender 
FROM customer.custdata
WHERE customer_id IN( SELECT DISTINCT cust_id FROM transactions.transdata);

-- 27. List transactions with total amount greater than the avg transaction amount.
SELECT *
FROM transactions.transdata
WHERE total_amt > (SELECT AVG(total_amt) FROM transactions.transdata);

-- 28. Show product categories that have never been purchased.
SELECT prod_cat
FROM prodcat.prodata
WHERE prod_cat_code NOT IN( SELECT DISTINCT prod_cat_code FROM transactions.transdata);

-- 29. Find customers who have no transactions.
SELECT customer_id, Gender, city_code
FROM customer.custdata
WHERE customer_id NOT IN (SELECT DISTINCT cust_id FROM transactions.transdata);

-- 30. Get transactions where the quantity is greater than the avg quantity.
SELECT *
FROM transactions.transdata
WHERE Qty > (SELECT AVG(Qty) FROM transactions.transdata);

-- 31. List customers who spent more than 10000 in total.
SELECT customer_id, gender, city_code
FROM customer.custdata
WHERE customer_Id IN (SELECT cust_id FROM transactions.transdata GROUP BY cust_id HAVING SUM(total_amt) > 10000);

-- 32. Find products purchased by customers from city_code = 10.
SELECT DISTINCT p.prod_subcat
FROM prodcat.prodata p
WHERE (p.prod_cat_code, p.prod_sub_cat_code) IN 
(SELECT t.prod_cat_code, t.prod_subcat_code
 FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
WHERE c.city_code = 10); 

-- 33. Show store types with revenue above the average store revenue
SELECT Store_type
FROM transactions.transdata 
GROUP BY store_type
HAVING SUM(total_amt) > 
(SELECT AVG(total_revenue) 
FROM
(SELECT SUM(total_amt) As Total_revenue 
FROM transactions.transdata v
GROUP BY store_type) As Store_data); 

-- 34. List customers who bought from at least two different store types.
SELECT customer_id
FROM customer.custdata
WHERE customer_id IN (SELECT cust_id FROM transactions.transdata 
GROUP BY cust_id HAVING COUNT(DISTINCT store_type) >=2 );

-- 35. Find the highest total amount spent in a single transaction
SELECT *
FROM transactions.transdata
WHERE total_amt = (SELECT MAX(total_amt) FROM transactions.transdata);

-- 36. Get the top 3 customers by total spending 
SELECT customer_id, Total_spent
FROM 
(SELECT cust_id AS customer_id, SUM(total_amt) AS Total_spent
 FROM transactions.transdata 
 GROUP BY cust_id
 ORDER BY Total_spent DESC
 LIMIT 3) AS Top_customers;
 
 -- 37. Show customers who purchased only one product category.
 SELECT customer_id
 FROM customer.custdata
 WHERE customer_Id IN (SELECT cust_id FROM transactions.transdata GROUP BY cust_id HAVING COUNT(DISTINCT prod_cat_code) = 1); 
 
 -- 38. Find product subcategories with revenue above the overall average revenue.
 SELECT prod_subcat
 FROM prodcat.prodata
 WHERE prod_sub_cat_code IN (SELECT prod_subcat_code 
 FROM transactions.transdata
 GROUP BY prod_subcat_code 
 HAVING SUM(total_amt) > (SELECT AVG(total_amt) FROM transactions.transdata)
 );
 
 -- 39. List transactions for the customer who made the maximum total spending .
 SELECT *
 FROM transactions.transdata
 WHERE cust_id = (SELECT cust_id FROM transactions.transdata GROUP BY cust_id ORDER BY SUM(total_amt) DESC LIMIT 1);
 
 -- 40. Show cities with no female customers.
 SELECT City_code
 FROM customer.custdata
 WHERE city_code NOT IN (SELECT DISTINCT city_code FROM customer.custdata WHERE Gender = 'F');    
 
 -- 41. Advance Find the percentage contribution of each product category to total sales.
 SELECT p.prod_cat, ROUND(SUM(t.total_amt) * 100 / (SELECT SUM(total_amt) FROM transactions.transdata), 2) AS Contribution_Percentage
 FROM transactions.transdata t
 JOIN prodcat.prodata p
 ON t.prod_cat_code = p.prod_cat_code
 GROUP BY p.prod_cat;
 
 -- 42. Get customers who bought the most expensive product (by rate).
 SELECT customer_id, gender
 FROM customer.custdata 
 WHERE customer_id IN (SELECT cust_id FROM transactions.transdata 
 WHERE Rate = (SELECT MAX(Rate) FROM transactions.transdata) );
 
 -- 43. Find the product category with the highest total tax collected.
 SELECT prod_cat
 FROM prodcat.prodata
 WHERE prod_cat_code = (SELECT prod_cat_code 
 FROM transactions.transdata 
 GROUP BY prod_cat_code 
 ORDER BY SUM(tax) DESC
 LIMIT 1);
 
 -- 44. Show customers whose average spending per transaction is above overall avg.
 SELECT customer_id
 FROM customer.custdata
 WHERE customer_Id IN (SELECT cust_id 
 FROM transactions.transdata
 GROUP BY cust_id
 HAVING avg(total_amt) > (SELECT avg(total_amt) FROM transactions.transdata));
 
 -- 45. Find transaction where the tax paid is above the category-wise average tax.
 SELECT *
 FROM transactions.transdata t
 WHERE t.tax > (SELECT avg(tax) FROM transactions.transdata WHERE prod_cat_code = t.prod_cat_code);
 
 -- using CTE
 
 -- 46. CTE Total sales per product category
  WITH category_sales AS (SELECT p.prod_cat, SUM(t.Qty) As Total_Qty, SUM(t.total_amt) AS Total_sales
 FROM transactions.transdata t
 JOIN prodcat.prodata p
 ON t.prod_cat_code = p.prod_cat_code
 GROUP BY p.prod_cat)
 SELECT * FROM category_sales;
 
 -- 47. Avg quantity sold per customer
 WITH sold_per AS (SELECT cust_id, AVG(Qty) As Avg_qty
 FROM transactions.transdata 
 GROUP BY cust_id)
 SELECT * FROM sold_per;
 
 -- 48. customers with total purchase > 5000
 WITH Total_cust AS (SELECT cust_id, SUM(total_amt) AS Total_purchase 
 FROM transactions.transdata 
 GROUP BY cust_id)
 SELECT cust_id, Total_purchase
 FROM Total_cust
 WHERE Total_purchase > 5000;
 
 -- 49. Highest selling product category
 WITH category_sell AS (SELECT p.prod_cat, SUM(total_amt) AS total_sales
 FROM transactions.transdata t
 JOIN prodcat.prodata p
 ON t.prod_cat_code = p.prod_cat_code
 GROUP BY p.prod_cat)
 SELECT prod_cat, total_sales
 FROM category_sell
 ORDER BY total_sales DESC
 LIMIT 1;
 
 -- 50. Total customers per city
 WITH city_cust AS (SELECT city_code, COUNT(DISTINCT customer_id) AS Total_customer
 FROM customer.custdata
 GROUP BY city_code)
 SELECT * FROM city_cust;
 
 -- 51. Monthly sales
  WITH monthly_sales AS (
    SELECT DATE_FORMAT(STR_TO_DATE(tran_date, '%d-%m-%Y'), '%Y-%m') AS month,
           SUM(total_amt) AS total_sales
    FROM transactions.transdata
    GROUP BY DATE_FORMAT(STR_TO_DATE(tran_date, '%d-%m-%Y'), '%Y-%m')
)
SELECT * FROM monthly_sales;

-- 52. Customers with more than 10 transactions
WITH Tran_cust AS (SELECT cust_id, COUNT(*) AS Total_trans
FROM transactions.transdata
GROUP BY cust_id)
SELECT cust_id, total_trans
FROM Tran_cust
WHERE total_trans > 10; 

-- 53. GENDER wise total sales
WITH Total_sales As (SELECT c.gender, SUM(t.total_amt) AS Total_sales
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.gender)
SELECT * FROM Total_sales;

-- 54. Most purchased subcategory
WITH pur_subcat AS (SELECT p.prod_subcat, SUM(t.Qty) AS Total_Qty
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code AND t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat)
SELECT prod_subcat, Total_Qty
FROM pur_subcat
ORDER BY Total_Qty DESC
LIMIT 1; 

-- 55. Average transaction value 
WITH Avg_tran AS (SELECT AVG(total_amt) As Total_avg
FROM transactions.transdata)
SELECT * FROM Avg_tran;

-- 56. Customers Born After 2000
WITH young_born AS ( SELECT customer_id, DOB
FROM customer.custdata
WHERE DOB > '2000-01-01')
SELECT * FROM young_born; 

-- 57. Total tax collected per category
WITH Tax_cat AS ( SELECT p.prod_cat, SUM(t.tax) AS Total_tax
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat)
SELECT * FROM Tax_cat;

-- 58. City with minimum customer
WITH min_cust AS (SELECT city_code, COUNT(*) AS Mini_cust
FROM customer.custdata
GROUP BY city_code)
SELECT city_code, Mini_cust
FROM min_cust
ORDER BY Mini_cust DESC
LIMIT 1;

-- 59. Transaction with Above-Average Quantity
WITH Total_Tran As (SELECT AVG(Qty) As Total_Qty
FROM transactions.transdata)
SELECT * FROM transactions.transdata
WHERE Qty> (SELECT Total_Qty FROM Total_Tran);

-- 60. Customers with zero transactions
WITH Zero_tran As (SELECT DISTINCT cust_id
FROM transactions.transdata)
SELECT c.customer_id
FROM customer.custdata c
LEFT JOIN Zero_tran z
ON c.customer_Id = z.cust_id
WHERE z.cust_id IS NULL;

-- 61. Total Revenue by year
WITH Yearly_sales AS (SELECT YEAR(tran_date) As year, SUM(total_amt) As tot_revenue
FROM transactions.transdata
GROUP BY YEAR(tran_date)
)
SELECT * FROM Yearly_sales;

-- 62. Most valuable customer
WITH most_cust As (SELECT cust_id, SUM(total_amt) AS Total_sales
FROM transactions.transdata
GROUP BY cust_id
)
SELECT cust_id, Total_sales
FROM most_cust
ORDER BY Total_sales DESC
LIMIT 1; 

-- 63. Top 3 product categories by Quantity
WITH Top_cat AS (SELECT p.prod_cat, SUM(t.Qty) AS Total_Qty
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code 
GROUP BY p.prod_cat
)
SELECT prod_cat, Total_Qty
FROM Top_cat
ORDER BY Total_Qty DESC
LIMIT 3;

-- 64. Total customer by geneder and city 
WITH gender_city As (SELECT city_code, Gender, COUNT(customer_id) As Total_cust
FROM customer.custdata
GROUP BY gender, city_code
)
SELECT * FROM gender_city;

-- 65. Total Discount given (Assumin discount = Rate * Qty - total_amt)
WITH Discount As (
SELECT SUM((Rate * Qty) - total_amt) AS Total_discount
FROM transactions.transdata
)
SELECT * FROM Discount;

-- 66. Avg age of customers
WITH Cust_age AS ( SELECT timestampdiff(YEAR,DOB,CURDATE()) As age
FROM customer.custdata
)
SELECT AVG(age) As Average_age
FROM Cust_age;

-- 67. product never purchased
WITH No_pur AS (SELECT prod_subcat_code
FROM transactions.transdata
)
SELECT p.prod_subcat
FROM prodcat.prodata p
LEFT JOIN No_pur n
ON p.prod_sub_cat_code = n.prod_subcat_code
WHERE n.prod_subcat_code IS NULL;

-- 68. City with highest total purchas
WITH Total_pur AS (SELECT c.city_code, SUM(t.total_amt) As Total_sales
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.city_code
)
SELECT city_code, Total_sales
FROM Total_pur
ORDER BY Total_sales DESC
LIMIT 1;

-- 69. Male vs Female Avg transaction value
WITH Avg_value AS (SELECT c.gender, AVG(t.total_amt) AS Avg_total
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id 
GROUP BY c.gender
)
SELECT * FROM Avg_value;

-- 70. Top 5 customers by number of products purchased
WITH No_prod As (SELECT cust_id, SUM(qty) As Total_prod
FROM transactions.transdata 
GROUP BY cust_id
)
SELECT cust_id, Total_prod
FROM No_prod
ORDER BY Total_prod DESC
LIMIT 5;

-- using CASE

-- 71. CASE Categorize Quantity as 'Low', 'Medium', or 'High'
SELECT transaction_id, Qty,
CASE 
	WHEN Qty <=2 THEN 'Low'
    WHEN Qty BETWEEN 3 AND 5 THEN 'Medium'
    ELSE 'High'
END AS qty_category
FROM transactions.transdata;

-- 72. Determine Transaction Type (High/Low Value)
SELECT transaction_id, total_amt,
CASE 
	WHEN total_amt >= 5000 THEN 'High Value'
    ELSE 'Low Value'
END AS transaction_type
FROM transactions.transdata;

-- 73. Gender Labeling
SELECT customer_id, gender,
CASE
	WHEN gender = 'M' THEN 'MALE'
    WHEN gender = 'F' THEN 'FEMALE'
    ELSE 'Other'
END AS Gender_label
FROM customer.custdata;

-- 74. Age Group Classification
SELECT customer_Id,
       TIMESTAMPDIFF(YEAR, DOB, CURDATE()) AS age,
       CASE
           WHEN TIMESTAMPDIFF(YEAR, DOB, CURDATE()) < 18 THEN 'Minor'
           WHEN TIMESTAMPDIFF(YEAR, DOB, CURDATE()) BETWEEN 18 AND 40 THEN 'Adult'
           ELSE 'Senior'
       END AS age_group
FROM customer.custdata;

-- 75. Tax Bracket Categorization
SELECT transaction_id, tax,
CASE
	WHEN tax = 0 THEN 'No tax'
    WHEN tax BETWEEN 1 AND 50 THEN 'Low tax'
    WHEN tax BETWEEN 51 AND 200 THEN 'Medium tax'
    ELSE 'High tax'
END AS tax_category
FROM transactions.transdata;

-- 76. Product Category Type
SELECT prod_cat_code, prod_cat,
CASE
	WHEN prod_cat IN ('Electronics', 'computers') THEN 'Tech'
    WHEN prod_cat IN ('Clothing', 'Shoes') THEN 'Fashion'
    ELSE 'Other'
END AS category_type
FROM prodcat.prodata;

-- 77. Weekend vs Weekday Transactions
SELECT transaction_id, tran_date,
CASE
	WHEN DAYOFWEEK(tran_date) IN (1,7) THEN 'Weekend'
    ELSE 'Weekday'
END AS day_type
FROM transactions.transdata;

-- 78. Profitability Check
SELECT transaction_id, Qty, Rate, total_amt,
CASE
	WHEN (Rate * Qty) - total_amt > 0 THEN 'Discounted'
    ELSE 'Full Price'
END AS Price_status
FROM transactions.transdata;

-- 79. Customer City Category
SELECT customer_id, city_code,
CASE
	WHEN city_code BETWEEN 2 AND 5 THEN 'Metro'
    WHEN city_code BETWEEN 6 AND 10 THEN 'Urban'
    ELSE 'Rural'
END As city_category
FROM customer.custdata;

-- 80. Product Popularity by Sales
SELECT p.prod_subcat,
CASE 
	WHEN SUM(t.Qty) > 100 THEN 'High popular'
    WHEN SUM(t.Qty) BETWEEN 70 AND 100 THEN 'Moderately popular'
    ELSE 'Less popular'
END AS popularity
FROM prodcat.prodata p
JOIN transactions.transdata t
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat;

-- 81. Transaction Discount Status
SELECT transaction_id, (Rate * Qty) - total_amt AS discount,
CASE 
	WHEN (Rate * Qty) - total_amt = 0 THEN 'No discount'
    ELSE 'Discount Applied'
END AS Discount_status
FROM transactions.transdata;

-- 82. Customer Loyalty
SELECT c.customer_id, COUNT(t.transaction_id) AS Total_tran,
CASE 
	WHEN COUNT(t.transaction_id) >= 20 THEN 'Platinum'
    WHEN COUNT(t.transaction_id) BETWEEN 10 AND 19 THEN 'Gold'
    ELSE 'Silver'
END AS loyalty
FROM customer.custdata c
LEFT JOIN transactions.transdata t 
ON c.customer_Id = t.cust_id
GROUP BY c.customer_id;

-- 83. Revenue Performance by Category
SELECT p.prod_cat, SUM(t.total_amt) AS Total_sales,
CASE
	WHEN SUM(t.total_amt) > 5000 THEN 'Excellent'
    WHEN SUM(t.total_amt) BETWEEN 20000 AND 50000 THEN 'Good'
    ELSE 'Poor'
END AS performance_cat
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 84. High Tax Transactions Flag
SELECT transaction_id, tax,
CASE 
	WHEN tax > 100 THEN 1
    ELSE 0
END AS High_tax
FROM transactions.transdata;

-- 85. Age Category for Customers Without DOB
SELECT customer_id, 
CASE
	WHEN DOB IS NULL THEN 'Unknown'
    ELSE 'known'
END AS DOB_cat 
FROM customer.custdata;

-- 86. Yearly Sales Classification
SELECT YEAR(tran_date) AS sales_year,
       SUM(total_amt) AS total_sales,
       CASE
           WHEN SUM(total_amt) > 100000 THEN 'High Revenue'
           ELSE 'Low Revenue'
       END AS revenue_class
FROM transactions.transdata
GROUP BY YEAR(tran_date);

-- 87. Gender-Based Offer Eligibility
SELECT customer_id, gender,
 CASE
	WHEN Gender = 'F' THEN 'Eligible for Women Offer'
	ELSE 'No Special Offer'
END AS offer_status
FROM customer.custdata;

-- 88. Refund Risk Check (Negative Total Amount)
SELECT transaction_id, total_amt,
CASE
	WHEN total_amt > 0 THEN 'Refund'
    ELSE 'Valid sale'
END AS sale_status
FROM transactions.transdata;

-- 89. Segment Customers by Purchase Frequency
SELECT cust_id, COUNT(*) AS purchase_count,
CASE
	WHEN COUNT(*) >=30 THEN 'Frequent Buyer'
	WHEN COUNT(*) BETWEEN 10 AND 29 THEN 'Regular Buyer'
	ELSE 'Occasional Buyer'
END AS customer_segment
FROM transactions.transdata
GROUP BY cust_id;

-- 90. Flag Transactions Without Tax
SELECT transaction_id, tax,
CASE
	WHEN tax IS NULL OR Tax = 0 THEN 'No Tax'
    ELSE 'Taxed'
END AS tax_status
FROM transactions.transdata;

-- 91. Classify Product Categories by Code
SELECT prod_cat_code,
CASE
	WHEN prod_cat_code < 5 THEN 'Group A'
    WHEN prod_cat_code BETWEEN 5 AND 10 THEN 'Group B'
    ELSE 'Group C'
END AS Product_cat
FROM prodcat.prodata;

-- 92. Weekend High-Spender Flag
SELECT transaction_id, total_amt, tran_date,
CASE
	WHEN DAYOFWEEK(tran_date) IN (1,7) AND total_amt > 5000 THEN 'Weekend High Spender'
	ELSE 'Normal'
END AS spend_flag
FROM transactions.transdata;

-- 93. Categorize Quantity with NULL Handling
SELECT transaction_id, Qty,
CASE
	WHEN Qty IS NULL THEN 'Unknown'
	WHEN Qty <= 1 THEN 'Low'
	ELSE 'Normal'
END AS Qty_label
FROM transactions.transdata;

-- 94. Identify High vs Low Product Return Risk
SELECT p.prod_subcat,
CASE
    WHEN SUM(t.Qty) < 10 THEN 'High Return Risk'
	ELSE 'Low Return Risk'
END AS return_risk
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat;

-- 95. Flag Inactive Customers
SELECT c.customer_Id,
CASE
	WHEN t.cust_id IS NULL THEN 'Inactive'
	ELSE 'Active'
END AS status
FROM customer.custdata c
LEFT JOIN transactions.transdata t
ON c.customer_Id = t.cust_id;

-- using SET Operator 

-- 96. Combine All Customer IDs from Transactions and Customer Table (UNION)
SELECT cust_id AS customer_id
FROM transactions.transdata
UNION
SELECT customer_Id
FROM customer.custdata;

-- 97. Combine All Customer IDs Including Duplicates (UNION ALL)
SELECT cust_id AS customer_id
FROM transactions.transdata
UNION ALL
SELECT customer_Id
FROM customer.custdata;

-- 98. Customers Who Have Transactions but Not in Customer Table (EXCEPT/MINUS).
SELECT cust_id
FROM transactions.transdata 
EXCEPT
SELECT customer_Id
FROM customer.custdata;

-- 99. Customers Present in Both Transaction and Customer Tables (INTERSECT).
SELECT cust_id
FROM transactions.transdata
INTERSECT
SELECT customer_Id
FROM customer.custdata;

-- 100. Product Categories Appearing in Transactions but Not in Product Table
SELECT prod_cat_code
FROM transactions.transdata
EXCEPT
SELECT prod_cat_code
FROM prodcat.prodata;

-- 101. Product Categories Present in Both Tables
SELECT prod_cat_code
FROM transactions.transdata
INTERSECT
SELECT prod_cat_code
FROM prodcat.prodata;

-- 102. All Product Categories from Transactions and Product Table (UNION).
SELECT prod_cat_code
FROM transactions.transdata
UNION
SELECT prod_cat_code
FROM prodcat.prodata;

-- 103. Customers Who Made Transactions but Have No Gender Data
SELECT cust_id
FROM transactions.transdata
EXCEPT
SELECT customer_Id
FROM customer.custdata
WHERE Gender IS NOT NULL;

-- 104. Customers Who Bought from Category 1 or Category 2 (UNION)
SELECT cust_id
FROM transactions.transdata
WHERE prod_cat_code = 1
UNION
SELECT cust_id
FROM transactions.transdata
WHERE prod_cat_code = 2;

-- 105. Customers with Transactions Having Qty < 2 or Qty > 10 (UNION)
SELECT cust_id, Qty
FROM transactions.transdata
WHERE Qty < 2
UNION
SELECT cust_id, Qty
FROM transactions.transdata
WHERE Qty > 10;

-- Aggregate Functions

-- 106. Count Total Transactions
SELECT COUNT(*) AS Total_Transactions
FROM transactions.transdata;

-- 107. Total Quantity Sold
SELECT SUM(Qty) AS total_quantity
FROM transactions.transdata;

-- 108. Average Transaction Amount
SELECT AVG(total_amt) AS avg_transaction_amount
FROM transactions.transdata;

-- 109. Maximum Transaction Value
SELECT MAX(total_amt) AS highest_transaction
FROM transactions.transdata;

-- 110. Minimum Transaction Value
SELECT MIN(total_amt) AS lowest_transaction
FROM transactions.transdata;

-- 111. Total Sales per Product Category
SELECT p.prod_cat, SUM(t.total_amt) AS total_sales
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 112. Total Quantity Sold per Subcategory
SELECT p.prod_subcat, SUM(t.Qty) AS total_quantity
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat;

-- 113. Number of Customers per City
SELECT city_code, COUNT(customer_Id) AS total_customers
FROM customer.custdata
GROUP BY city_code;

-- 114. Gender-wise Customer Count
SELECT Gender, COUNT(*) AS customer_count
FROM customer.custdata
GROUP BY Gender;

-- 115. Average Tax Paid per Transaction
SELECT AVG(Tax) AS avg_tax
FROM transactions.transdata;

-- 116. Total Revenue per Year
SELECT YEAR(tran_date) AS sales_year,
       SUM(total_amt) AS total_revenue
FROM transactions.transdata
GROUP BY YEAR(tran_date);

-- 117. Average Quantity per Transaction
SELECT AVG(Qty) AS avg_quantity
FROM transactions.transdata;

-- 118. Highest Spending Customer
SELECT cust_id, SUM(total_amt) AS total_spent
FROM transactions.transdata
GROUP BY cust_id
ORDER BY total_spent DESC
LIMIT 1;

-- 119. Total Number of Unique Customers
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM transactions.transdata;

-- 120. Product Category with Maximum Quantity Sold
SELECT p.prod_cat, SUM(t.Qty) AS total_quantity
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat
ORDER BY total_quantity DESC
LIMIT 1;

-- 121. Average Age of Customers
SELECT AVG(TIMESTAMPDIFF(YEAR, DOB, CURDATE())) AS avg_age
FROM customer.custdata;

-- 122. Total Discount Given
SELECT SUM((Rate * Qty) - total_amt) AS total_discount
FROM transactions.transdata;

-- 123. Total Tax Collected per Product Category
SELECT p.prod_cat, SUM(t.Tax) AS total_tax
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 124. Count Transactions per Customer
SELECT cust_id, COUNT(transaction_id) AS transaction_count
FROM transactions.transdata
GROUP BY cust_id;

-- 125. Average Spending per Customer
SELECT cust_id, AVG(total_amt) AS avg_spending
FROM transactions.transdata
GROUP BY cust_id;

-- 126. Minimum and Maximum Quantity per Product Subcategory
SELECT p.prod_subcat,
       MIN(t.Qty) AS min_quantity,
       MAX(t.Qty) AS max_quantity
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat;

-- 127. Total Revenue per City
SELECT c.city_code, SUM(t.total_amt) AS total_sales
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.city_code;

-- 128. Average Quantity Purchased by Gender
SELECT c.Gender, AVG(t.Qty) AS avg_quantity
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.Gender;

-- 129. Product Subcategory with Lowest Sales
SELECT p.prod_subcat, SUM(t.total_amt) AS total_sales
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat
ORDER BY total_sales ASC
LIMIT 1;

-- 130. Total Transactions and Revenue for Each Customer
SELECT cust_id,
       COUNT(transaction_id) AS total_transactions,
       SUM(total_amt) AS total_revenue
FROM transactions.transdata
GROUP BY cust_id;

-- 131. Find the Average Quantity per Product Category
SELECT p.prod_cat, AVG(t.Qty) AS avg_quantity
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 132. Find the Total Tax Collected by Each Store Type
SELECT Store_type, SUM(Tax) AS total_tax
FROM transactions.transdata
GROUP BY Store_type;

-- 133. Find the Total Revenue per Gender
SELECT c.Gender, SUM(t.total_amt) AS total_revenue
FROM transactions.transdata t
JOIN customer.custdata c
ON t.cust_id = c.customer_Id
GROUP BY c.Gender;

-- 134. Find the Maximum Transaction Amount per Store Type
SELECT Store_type, MAX(total_amt) AS max_transaction
FROM transactions.transdata
GROUP BY Store_type;

-- 135. Count the Number of Transactions for Each Product Subcategory
SELECT p.prod_subcat, COUNT(t.transaction_id) AS transaction_count
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_subcat;

-- 136. Find Customers Who Purchased More Than 5 Units in Total
SELECT cust_id, SUM(Qty) AS total_units
FROM transactions.transdata
GROUP BY cust_id
HAVING SUM(Qty) > 5;

-- 137. Find the Average Spending of Customers Who Spent More Than 10,000
SELECT cust_id, AVG(total_amt) AS avg_spending
FROM transactions.transdata
GROUP BY cust_id
HAVING SUM(total_amt) > 10000;

-- 138. Find the Total Discount Given per Product Category
SELECT p.prod_cat, SUM((t.Rate * t.Qty) - t.total_amt) AS total_discount
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat;

-- 139. Find the Minimum and Maximum Transaction Amount per Customer
SELECT cust_id, MIN(total_amt) AS min_transaction,
       MAX(total_amt) AS max_transaction
FROM transactions.transdata
GROUP BY cust_id;

-- 140. Find the Total Revenue per Product Category for Each Store Type
SELECT p.prod_cat, t.Store_type, SUM(t.total_amt) AS total_revenue
FROM transactions.transdata t
JOIN prodcat.prodata p
ON t.prod_cat_code = p.prod_cat_code
GROUP BY p.prod_cat, t.Store_type;

 